version: "3.1"
services:
  my_csv:
    image: infracloudio/csvserver:latest
    volumes:
      -  "/csvserver/solution/inputFile:/csvserver/inputdata"
    ports:
      - "9393:9300"
    environment:
      - CSVSERVER_BORDER=Orange
    networks:
      - stack
  prometheus:
    image: prom/prometheus:v2.22.0
    volumes: 
      - "/csvserver/solution/prometheus.yml:/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
    networks:
      - stack
networks:
  stack:
 
