version: "3.1"
services:
  my_csv:
    image: infracloudio/csvserver:latest
    volumes:
      -  "/csvserver/solution/inputFile:/csvserver/inputdata"
    ports:
      - "9393:9300"
    environment:
      - CSVSERVER_BORDER=Orange 
